CREATE DATABASE ORG;
SHOW DATABASES;
USE ORG;

CREATE TABLE Worker(
WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(25),
LAST_NAME VARCHAR(25),
SALARY INT(25),
JOINING_DATE DATE,
DEPERTMENT CHAR(10)
);

INSERT INTO Worker VALUES(1,"TARUN",'DALBERA',10000,"12/12/12","IT");
INSERT INTO Worker (WORKER_ID,FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPERTMENT) VALUES 
(2,'ARUN','DALBERA',10000,'12/12/12','IT');

SELECT * FROM Worker;

CREATE TABLE Bonus(
WORKER_REF_ID INT,
BONUS_AMOUNT INT(15),
BONUS_DATE DATE,
FOREIGN KEY(WORKER_REF_ID)
REFERENCES Worker(WORKER_ID)
ON DELETE CASCADE
);

INSERT INTO Bonus(WORKER_REF_ID,BONUS_AMOUNT,BONUS_DATE) VALUES
(1,5000,"1-5-20"),
(2,4000,"1-5-23");

SELECT * FROM Bonus;

CREATE TABLE Title(
WORKER_REF_ID INT,
WORKER_TIILE CHAR(25),
AFFECTED_FROM DATETIME,
FOREIGN KEY (WORKER_REF_ID)
REFERENCES Worker(WORKER_ID)
ON DELETE CASCADE
);

INSERT INTO Title (WORKER_REF_ID,WORKER_TIILE,AFFECTED_FROM) VALUES
(1,"manager","10-12-20"),
(2,"executive","15-03-19");

ALTER TABLE Title
RENAME COLUMN WORKER_TIILE TO WORKER_TITLE;

SELECT * FROM Title;







